spring:
  profiles:
    active: local
  application:
    name: TaskManagementApplication

app:
  token:
    expiration: ${LOCAL_JWT_ACC_TIME}
    refresh-expiration: ${LOCAL_JWT_REF_TIME}
    secret: ${LOCAL_JWT_SECRET}