spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PROD_EMAIL_USER}
    password: ${PROD_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  token:
    expiration: ${PROD_JWT_ACC_TIME}
    refresh-expiration: ${PROD_JWT_REF_TIME}
    secret: ${PROD_JWT_SECRET}