spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:33542/railway
    username: postgres
    password: MMfRKLgtHIJtkuTQEdkynRkkFKsnuhuZ
  mail:
    host: smtp.gmail.com
    port: 587
    username: almustaphat.tukur@gmail.com
    password: hlyisvlwobmekpbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#spring:
#  sql:
#    init:
#      mode: always
#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#  datasource:
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}}
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: almustaphat.tukur@gmail.com
#    password: hlyisvlwobmekpbu
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
app:
  token:
    expiration: 180000
    refresh-expiration: 360000
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970