spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:33542/railway
    username: postgres
    password: MMfRKLgtHIJtkuTQEdkynRkkFKsnuhuZ
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  token:
    expiration: 3600000
    refresh-expiration: 7200000
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
